# Generated by Django 5.1.1 on 2024-10-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sage_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="related_posts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select posts related to this product.",
                to="sage_blog.post",
                verbose_name="Related posts",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="suggested_posts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select other posts to suggest alongside this product.",
                to="sage_blog.post",
                verbose_name="Suggested posts",
            ),
        ),
    ]
