# Generated by Django 5.1.2 on 2025-02-03 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sage_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                max_length=110,
                null=True,
                upload_to="blog/posts/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "ogv"]
                    )
                ],
                verbose_name="Video",
            ),
        ),
    ]
